### ISSUE TITLE
ERROR in ./node_modules/ng-select2/fesm5/ng-select2.js Module build failed

### ISSUE THREAD

**Issue by princekdwivedi** [NejcZdovc/ng2-select2#147]
ERROR in ./node_modules/ng-select2/fesm5/ng-select2.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (F:\xampp\htdocs\aeveenxt.com\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (F:\xampp\htdocs\aeveenxt.com\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (F:\xampp\htdocs\aeveenxt.com\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (F:\xampp\htdocs\aeveenxt.com\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (F:\xampp\htdocs\aeveenxt.com\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (F:\xampp\htdocs\aeveenxt.com\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (F:\xampp\htdocs\aeveenxt.com\node_modules\typescript\lib\typescript.js:16599:21)

"ng-select2": "^1.2.1",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "select2": "^4.0.4",

**Comment by andressan95** [comment]
try change "ng-select2": "^1.2.1", to "ng-select2": "1.2.0", this work for me in angular 8.0.0
