### ISSUE TITLE
Issue with Jasmine testing when importing ng2select2 module

### ISSUE THREAD

**Issue by xtoff** [NejcZdovc/ng2-select2#71]
Hello,

I have a issue with all my tests that run AFTER if I import "Select2Module" in my testing class. 
When I run my tests, they all succeed, until it runs the test class that imports "Select2Module", then this class and all the classes after fail with the same error (Cannot read property 'off' of undefined):

`Chrome 56.0.2924 (Mac OS X 10.12.3) AppComponent should render title in a h1 tag FAILED
        TypeError: Cannot read property 'off' of undefined
            at Select2Component.ngOnDestroy (webpack:///~/ng2-select2/ng2-select2.component.js:73:0 <- src/test.ts:48442:21)
            at Wrapper_Select2Component.ngOnDestroy (/Select2Module/Select2Component/wrapper.ngfactory.js:19:16)
            at CompiledTemplate.proxyViewClass.View_AppComponent0.destroyInternal (/DynamicTestModule/AppComponent/component.ngfactory.js:66:30)
            at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- src/test.ts:61817:14)
            at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- src/test.ts:62220:38)
            at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.destroyInternal (/DynamicTestModule/AppComponent/host.ngfactory.js:33:19)
            at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- src/test.ts:61817:14)
            at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- src/test.ts:62220:38)
            at CompiledTemplate.proxyViewClass.AppView.detachAndDestroy (webpack:///~/@angular/core/src/linker/view.js:187:0 <- src/test.ts:61801:14)
            at ComponentRef_.destroy (webpack:///~/@angular/core/src/linker/component_factory.js:147:51 <- src/test.ts:31535:70)
            at ComponentFixture.destroy (webpack:///~/@angular/core/bundles/core-testing.umd.js:263:0 <- src/test.ts:16757:35)
            at webpack:///~/@angular/core/bundles/core-testing.umd.js:728:61 <- src/test.ts:17222:78
            at Array.forEach (native)
            at TestBed.resetTestingModule (webpack:///~/@angular/core/bundles/core-testing.umd.js:728:0 <- src/test.ts:17222:34)
            at Function.TestBed.resetTestingModule (webpack:///~/@angular/core/bundles/core-testing.umd.js:636:0 <- src/test.ts:17130:26)
`

It seems that the ng2select2 element is not defined on destroy. This explains why all my tests succeed before I run the test that imports "Select2Module". All tests after that import are failing.

I started a new angular 2 project with only the "Select2Module" and the error still remains. You can check out the project on: https://github.com/xtoff/ng2-select2-testing.

Can you fix this? :)
Thanks!

**Comment by Apee** [comment]
Any development on this issue we have the same problem ?

**Comment by NejcZdovc** [comment]
@Apee this should be fixed in the latest version 1.0.0-beta.16, where we added check for it. Are you using the latest version?
